const ADD_SITES = 'ADD_SITES';
const ADD_PLANTS = 'ADD_PLANTS';
const ADD_FUNCTIONS = 'ADD_FUNCTIONS';

const ADD_PRODUCTION='ADD_PRODUCTION'
const ADD_STARTDATE = 'ADD_STARTDATE';
const ADD_ENDDATE = 'ADD_ENDDATE';
const ADD_DRILLDOWNDATA = 'ADD_DRILLDOWNDATA'

export {
  ADD_STARTDATE,
  ADD_ENDDATE,
  ADD_PLANTS,
  ADD_SITES,
  ADD_FUNCTIONS,
  ADD_PRODUCTION,
  ADD_DRILLDOWNDATA,
}